server:
  port: 8080
application:
  name: ^project.artifactId^
  description: ^project.name^
  version: ^project.version^
spring:
  application:
    name: ^project.artifactId^
  jackson:
    serialization:
      write_dates_as_timestamps: false


#companyx-client-api: http://localhost:8080
companyx-client-api: https://us-central1-sesame-care-dev.cloudfunctions.net
